### ISSUE TITLE
Java 파일 에러

### ISSUE THREAD

**Issue by song-heeyoun** [madvirus/ddd-start#1]
**~ >>> 에러 파일 위치**

`ddd-start/src/main/java/com/myshop/order/infra/dao/JpaOrderSummaryDao.java`

자바 파일의 com.myshop.order.query.dto.OrderSummary_  존재하지 않는 **dto** 를 **import** 하고 있습니다.

com.myshop.order.query.dto.OrderSummary_ **dto** 삭제시 라인 **40** 번째에서 문제가 발생합니다

`criteriaQuery.orderBy(cb.desc(root.get(OrderSummary_.number)));`

OrderSummary_ >>> OrderSummary 변경해봤지만 의도를 몰라서 고치지 못하겠습니다. :)

확인 부탁드립니다.

**Comment by madvirus** [comment]
안녕하세요.

JPA의 정적메타모델이라는 것이 있는데
OrderSummay_가 이에 해당합니다.
이 클래스는 빌드 과정에서 생성ㄷ히는 클래스인데
이 클래스 생성 방법을 소스 사이트에 추가해야겠네요.
집에 돌아가면 추가하고 다시 메일 드릴게요.

최범균 드림.
1. 7. 30. 오전 2:38에 "song-heeyoun" notifications@github.com님이 작성:

**Comment by heeyoun-song** [comment]
감사합니다.

**Comment by madvirus** [comment]
https://github.com/madvirus/ddd-start의  README 파일에 생성 방법 추가했습니다.
